language: java
stages:
  - install
  - test

jobs:
  include:
    - stage: install
      script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      name: Build code

    - stage: test
      script: ./mvnw test -Dmaven.javadoc.skip=true -B -V
      name: Run tests

addons:
  sonarcloud:
    organization: "keratomi"
    token:
      secure: "travis encrypt a891222687743b343650b6a94ffdfbc9f9c81424" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Keratomi_deck-of-cards
